name: SAST_and_SCA_scan

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  do_polaris_and_blackduck:

    runs-on: ubuntu-latest

    env:
      PROJECT: MW-mock-http-server
      BLDCMD: mvn -B package -Dmaven.javadoc.skip=true -DskipTests
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      BLACKDUCK_SERVER_URL:  ${{ secrets.BLACKDUCK_SERVER_URL }}
      BLACKDUCK_ACCESS_TOKEN:  ${{ secrets.BLACKDUCK_ACCESS_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Polaris
      run: |
        curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -d /tmp -jo polaris_cli-linux64.zip
        /tmp/polaris --co project.name=$PROJECT analyze -w -- $BLDCMD

    - name: Detect
      uses: blackducksoftware/github-action@2.0.0
      with:
        args: '--blackduck.url="$BLACKDUCK_SERVER_URL" --blackduck.api.token="$BLACKDUCK_ACCESS_TOKEN" --detect.project.name="$PROJECT" --detect.risk.report.pdf=true'
